"""add teams and roles

Revision ID: ad9641bf7fa8
Revises: d086446d6ef0
Create Date: 2026-02-11 17:57:31.292411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ad9641bf7fa8'
down_revision: Union[str, None] = 'd086446d6ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inviterole_enum = postgresql.ENUM('admin', 'atleta', name='inviterole', create_type=False)
    inviterole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('invites', sa.Column('role', inviterole_enum, nullable=True))
    op.add_column('invites', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invites', 'teams', ['team_id'], ['id'])
    userrole_enum = postgresql.ENUM('admin', 'atleta', name='userrole', create_type=False)
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_column('invites', 'team_id')
    op.drop_column('invites', 'role')
    inviterole_enum = postgresql.ENUM('admin', 'atleta', name='inviterole')
    inviterole_enum.drop(op.get_bind(), checkfirst=True)
    userrole_enum = postgresql.ENUM('admin', 'atleta', name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
