"""add athlete profile

Revision ID: c59af22735c9
Revises: ad9641bf7fa8
Create Date: 2026-02-12 02:06:09.121506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c59af22735c9'
down_revision: Union[str, None] = 'ad9641bf7fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    posicao_enum = postgresql.ENUM(
        'goleiro', 'zagueiro', 'lateral', 'volante', 'meia', 'atacante', 'ponta',
        name='posicao', create_type=False
    )
    perna_enum = postgresql.ENUM(
        'direita', 'esquerda', 'ambidestra',
        name='pernaboa', create_type=False
    )
    perna_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS athlete_profiles (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
            nome VARCHAR(100),
            apelido VARCHAR(50),
            telefone VARCHAR(20),
            posicao posicao,
            perna_boa pernaboa,
            numero_camisa INTEGER,
            foto_url VARCHAR(500),
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ
        );
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_profiles')
    perna_enum = postgresql.ENUM('direita', 'esquerda', 'ambidestra', name='pernaboa')
    perna_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
