"""add auth tables

Revision ID: d086446d6ef0
Revises: 
Create Date: 2026-02-11 14:38:05.001460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd086446d6ef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    invite_status_enum = postgresql.ENUM('pendente', 'aceito', 'cancelado', 'expirado', name='invitestatus', create_type=False)
    invite_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('atletas', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atletas', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('nome', sa.String(length=100), nullable=True))
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'phone', new_column_name='telefone', existing_type=sa.VARCHAR())
    op.alter_column('users', 'password_hash', new_column_name='senha_hash', existing_type=sa.VARCHAR())
    op.alter_column('users', 'is_active', new_column_name='ativo', existing_type=sa.BOOLEAN())
    op.create_index(op.f('ix_users_telefone'), 'users', ['telefone'], unique=True)
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_column('users', 'is_admin')
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS invites (
            id SERIAL PRIMARY KEY,
            token VARCHAR(100) NOT NULL,
            racha_id INTEGER NOT NULL REFERENCES rachas(id),
            email VARCHAR(255),
            telefone VARCHAR(20),
            nome VARCHAR(100),
            status invitestatus,
            criado_por_user_id INTEGER REFERENCES users(id),
            criado_em TIMESTAMPTZ DEFAULT now(),
            aceito_em TIMESTAMPTZ,
            expira_em TIMESTAMPTZ,
            CONSTRAINT uq_invites_token UNIQUE (token)
        );
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_invites_token ON invites (token);")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS push_tokens (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id),
            token VARCHAR(255) NOT NULL,
            plataforma VARCHAR(50),
            criado_em TIMESTAMPTZ DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_push_tokens_token ON push_tokens (token);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    invite_status_enum = postgresql.ENUM('pendente', 'aceito', 'cancelado', 'expirado', name='invitestatus')
    invite_status_enum.drop(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'ativo', new_column_name='is_active', existing_type=sa.BOOLEAN())
    op.alter_column('users', 'senha_hash', new_column_name='password_hash', existing_type=sa.VARCHAR())
    op.alter_column('users', 'telefone', new_column_name='phone', existing_type=sa.VARCHAR())
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.drop_index(op.f('ix_users_telefone'), table_name='users')
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column('users', 'nome')
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.drop_column('atletas', 'user_id')
    # ### end Alembic commands ###
